name: Build
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jakoch/install-vulkan-sdk-action@v1.0.3
        with:
          vulkan_version: 1.4.341.1
          install_runtime: true
          cache: true
          stripdown: true
      - name: Configure
        run: cmake --preset wsl-release-gcc
      - name: Build
        run: cmake --build --preset wsl-release-gcc

  build-linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jakoch/install-vulkan-sdk-action@v1.0.3
        with:
          vulkan_version: 1.4.341.1
          install_runtime: true
          cache: true
          stripdown: true
      - name: Configure
        run: cmake --preset wsl-release-clang
      - name: Build
        run: cmake --build --preset wsl-release-clang

  build-windows-clang:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jakoch/install-vulkan-sdk-action@v1.0.3
        with:
          vulkan_version: 1.4.341.1
          install_runtime: true
          cache: true
          stripdown: true
      - name: Configure
        run: cmake --preset windows-debug-clang
      - name: Build
        run: cmake --build --preset windows-debug-clang
